import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_fonts/google_fonts.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'models/app_user.dart';
import 'services/auth_service.dart';
import 'screens/auth/login_screen.dart';
import 'screens/home_screen.dart';
import 'screens/content_screen.dart';
import 'screens/links_screen.dart';
import 'screens/admin/create_content_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const TruthBoundaryApp());
}

class TruthBoundaryApp extends StatelessWidget {
  const TruthBoundaryApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TruthBoundary',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1B5E20),
          brightness: Brightness.dark,
        ),
        textTheme: GoogleFonts.latoTextTheme(ThemeData.dark().textTheme),
        useMaterial3: true,
      ),
      home: const AuthWrapper(),
    );
  }
}

// Listens to auth state and shows Login or Main app accordingly
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = AuthService();

    return StreamBuilder<AppUser?>(
      stream: authService.userStream,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        final user = snapshot.data;
        if (user == null) return const LoginScreen();
        return MainNavigation(currentUser: user);
      },
    );
  }
}

class MainNavigation extends StatefulWidget {
  final AppUser currentUser;
  const MainNavigation({super.key, required this.currentUser});

  @override
  State<MainNavigation> createState() => _MainNavigationState();
}

class _MainNavigationState extends State<MainNavigation> {
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    final screens = [
      HomeScreen(currentUser: widget.currentUser),
      ContentScreen(currentUser: widget.currentUser),
      const LinksScreen(),
    ];

    return Scaffold(
      body: screens[_currentIndex],
      // Admins get a FAB to create new content
      floatingActionButton: widget.currentUser.isAdmin
          ? FloatingActionButton.extended(
              onPressed: () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) =>
                      CreateContentScreen(admin: widget.currentUser),
                ),
              ),
              icon: const Icon(Icons.add),
              label: const Text('New Card'),
            )
          : null,
      bottomNavigationBar: NavigationBar(
        selectedIndex: _currentIndex,
        onDestinationSelected: (i) => setState(() => _currentIndex = i),
        destinations: [
          const NavigationDestination(icon: Icon(Icons.home), label: 'Home'),
          const NavigationDestination(
              icon: Icon(Icons.menu_book), label: 'Content'),
          const NavigationDestination(icon: Icon(Icons.link), label: 'Connect'),
          // Sign out button for admins
          if (widget.currentUser.isAdmin)
            const NavigationDestination(
                icon: Icon(Icons.logout), label: 'Sign Out'),
        ],
      ),
    );
  }
}
